services:
  landing:
    build: .
    container_name: landing
    volumes:
      - .:/app
      - /app/node_modules
      - ./_logs:/root/.npm/_logs/
    networks:
      - caddy

  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis
    restart: always
    environment:
      COOKIE_DOMAIN: "ivantopgaming.ru"
      TARGET: "http://landing:3000"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "1h"
      OG_CACHE_CONSIDER_HOST: "true"
    networks:
      - caddy

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: analytics
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: <APP_SECRET>
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - caddy

  db:
    image: postgres:15-alpine
    container_name: landing_analytics_db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - caddy

      
volumes:
  umami-db-data:

networks:
  caddy:
    external: true